### ISSUE TITLE
Low ASR-Bleu result with simul-s2st.sh

### ISSUE THREAD

**Issue by arararz** [ictnlp/StreamSpeech#12]
Hi, I ran the preprocess script and the bash script on the es-en dataset following the instructions given using the pretrained model weights on huggingface. However, the resulting ASR-Bleu score was only 9.1. What might be the reason for this inaccuracy?

**Comment by arararz** [comment]
Turns out that I ran an unnormalized version of the test set and asr-bleu with silence, leading to low bleu scores.

**Comment by Typhoeus-Wang** [comment]
> Turns out that I ran an unnormalized version of the test set and asr-bleu with silence, leading to low bleu scores.

Hi, what's the unnormalized version of the test set? I also got a low ASR-Bleu score on test set and I'm trying to find whether I also ran the evaluation script on unnormalized version of the test set.

**Comment by tiannanzhang** [comment]
That shouldn't be a problem with the original test set; I didn't have enough memory to run it so I tried running a part of it, and did not get the part from the right location
